### ISSUE TITLE
Simplificaciones booleanas

### ISSUE THREAD

**Issue by JoseRodriguez-23620213** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-6#1]
[Simplificacion booleana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-6/files/13631631/Simplificacion.booleana.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
